name = "crypto-checker"
main = "build/index.js"
compatibility_date = "2026-03-16"

[build]
command = "cargo install -q \"worker-build@^0.7\" && worker-build --release"

[vars]
DEBUG = "true"
TIMEOUT = "true"
TIMEOUT_MS = "900"

[env.test.vars]
DEBUG = "true"
TIMEOUT = "false"
TIMEOUT_MS = "300"

[env.staging.vars]
DEBUG = "true"
TIMEOUT_MS = "300"

[env.production.vars]
DEBUG = "false"
TIMEOUT_MS = "300"
