name = "crypto-checker"
main = "build/index.js"
compatibility_date = "2026-03-16"

[build]
command = "cargo install -q \"worker-build@^0.7\" && worker-build --release"

[env.staging.vars]
DEBUG = "true"

[env.production.vars]
DEBUG = "false"
